analysis/customrules.yaml

This is not necessary and also recommended in
https://github.com/falcosecurity/falco/issues/1403.

Disable falco k8s audit logging webserver.

---

analysis/customrules.yaml
analysis/main.go

- Record opening paths even if they fail.
- Record stat syscalls on filepaths.
- Also add/simplify some exclusions.
- Remove /proc, /tmp from exclusions
For #40.

Catch more file accesses.

---

build/build_docker.sh
build/node/Dockerfile
build/python/Dockerfile
build/ruby/Dockerfile

Also docker build --squash.
This reduces the size of images to 1/8 their previous size and speeds up
analysis by a significant amount.

Use slim base images for the language analysis images.

---

analysis/analysis.go
analysis/npm.go
analysis/pypi.go
analysis/rubygems.go
build/analysis/Dockerfile
build/build_docker.sh
build/node/Dockerfile
build/node/analyze.js
build/python/Dockerfile
build/python/analyze.py
build/ruby/Dockerfile
build/ruby/analyze.rb

- Squash analysis images by default in the Dockerfiles. The previous method
didn't retain WORKDIR and env vars which caused issues.
- Exit cleanly if the package to be analysed is not found to avoid
unnecessary retries.
- More cleanly handle an harmless error message from gVisor.

Various fixes.

---

analysis/analysis.go
analysis/cmd/analyze.go
analysis/cmd/fillindexes.go
analysis/cmd/worker.go
analysis/config/deployment.yaml
analysis/go.sum

Firestore entities will serve as an index for the JSON stored on GCS.
This will be used to serve interactive queries/searches from a dashboard.

Write analysis results to firestore.

---

analysis/analysis.go

This led to inaccurate results as log files accumulate from past runs.

Fix bug with log files not being cleared in between worker runs.

---

analysis/cmd/worker.go
examples/e2e/docker-compose.yml
scheduler/main.go

Add retries to reduce hard failures in situations where the pubsub endpoint isn't ready or has a small outage. 
Currently the retry configurations are hard coded as constants, we could look at breaking these out into environment variables if the default is not sufficient for all use cases.
Resolves #81
Resolves #82

Add retries with backoff for scheduler/worker

---

README.md

The environment variable documentation in README.md was unclear due to bad spacing, this has been fixed.

Fix newline spacing in README

---

examples/e2e/docker-compose.yml

This pins the versions throughout the e2e docker-compose aside from those relating to package-feeds/analysis directly which use the latest available.
These can be pinned in the future to provide a more solid example but for now this allows us to easily identify breakages in the latest API / configurations.

Pin versions on e2e example images

---

scheduler/go.mod
scheduler/go.sum
scheduler/main.go

This updates the reference to package-feeds following the merge of https://github.com/ossf/package-feeds/pull/137, the feeds sub package has been moved into the pkg subdirectory.

Update package-feeds reference

---

.github/workflows/build-images.yml
analysis/Dockerfile
build/build_docker.sh

This allows for docker images to be built and pushed via github actions. Resolves #86
@oliverchang We will need to add the necessary secrets via the repository configuration for pushing to gcr.io

Add github action for build_docker on merge

---

server/go.mod
server/go.sum

Reverts ossf/package-analysis#137
Firebase v1.6.1 requires google.golang.org/api v0.59.0

Revert "Bump google.golang.org/api from 0.59.0 to 0.60.0 in /server"

---

internal/strace/strace.go

Fixes #163 
```
I1119 08:25:51.699708     173 strace.go:587] [   9] npm init E openat(AT_FDCWD /app, 0x7fc2d2f318b1 /etc/localtime, O_RDONLY|O_CLOEXEC, 0o0)
```

Improve the strace regex to capture task names with spaces.

---

.github/workflows/build-images.yml
build/build_docker.sh
cmd/analyze/Dockerfile
infra/worker/workers-set.yaml
internal/sandbox/sandbox.go

This causes various issues (such as compatibility on CI), and presents
scalability issues with larger images.
Instead, pull images on demand and cache them in persistent storage volume
on our workers. Make our workers a StatefulSet instead of Deployment to
support this.
This helps #146.

Stop caching sandbox images in analysis image.

---

cmd/analyze/main.go
cmd/worker/main.go
internal/analysis/analysis.go
internal/sandbox/sandbox.go

This also allows us to add a flag (`-nopull`) for disabling image pulling which is useful while developing sandbox images.
For example, to use a local container rather than a remote one the following can be done:
```
$ sudo apt install podman
$ sudo buildah pull docker-daemon:gcr.io/ossf-malware-analysis/node:latest
$ docker run -v /var/lib/containers:/var/lib/containers \
...
gcr.io/ossf-malware-analysis/analysis analyze \
...
-nopull
```

Improve the Sandbox API and have the Analysis know nothing about images.

---

README.md
cmd/analyze/main.go
cmd/worker/main.go
internal/analysis/analysis.go
internal/pkgecosystem/ecosystem.go
internal/pkgecosystem/npm.go
internal/pkgecosystem/pypi.go
internal/pkgecosystem/rubygems.go
internal/sandbox/sandbox.go
sandboxes/README.md
sandboxes/npm/Dockerfile
sandboxes/npm/analyze.js
sandboxes/pypi/Dockerfile
sandboxes/pypi/analyze.py
sandboxes/rubygems/Dockerfile
sandboxes/rubygems/analyze.rb

**Note**: This is a breaking change:
- new sandbox images won't work with old versions of the analyze and worker commands
- old sandbox images won't work with the updated analyze and worker commands.
Changes:
- update the spec slightly surrounding the usage of `--local FILE` and `--version VERSION`.
- support the `all` phase in dynamic analysis sandboxes.
- escapes package name, package filename and version when passing it through to the podman command to prevent shell command injection.
- requires `-package` to always be specified so that files being installed can be imported correctly.

Update the sandboxes to prepare them to fully support the new API.

---

internal/log/log.go

Didn't realise the zapdriver Core wasn't being used.
This re-adds it correctly.

Make sure the zapdriver Core is being used in prod.

---

sandboxes/npm/analyze.js

Turns out `Map.keys()`:
- returns an interator, not an `Array`
- requires `get(key)` to return the value for a given key.

Fix broken npm analyze.js command

---

.github/workflows/test.yml
README.md
internal/strace/strace.go
internal/strace/strace_test.go

Tests to help ensure the strace parsing works correctly.
- Remove `listen` for sockets as it doesn't actually include socket information.
- Change the socket pattern to allow the family to be pulled out so we can not log warnings when we encounter a socket we want to ignore.

Add some tests for strace and improve the parsing to make it less noisy.

---

build/build_docker.sh
build/cloudbuild.yaml
cmd/analyze/Dockerfile
cmd/analyze/main.go
cmd/worker/main.go
infra/terraform/analysis.tf
infra/terraform/build/main.tf
infra/terraform/build/variables.tf
infra/terraform/terraform.tfvars
internal/sandbox/sandbox.go

When this repo is tagged with a tag that matches the pattern `rel-[0-9]+` a cloud build trigger is fired that starts building docker images.
- The trigger is configured using terraform (currently deployed)
- The tag is used as a tag for docker container images
- The tag is used in the worker/analysis image to ensure the corresponding sandbox images are used - this is to ensure that the behavior between the two remains consistent.
Once a release has been tagged and the images built a `kubectl rollout restart statefulset/workers-set` should start the workers using the latest release version.

Support tagged releases for images

---

.dockerignore
cmd/analyze/Dockerfile
cmd/analyze/main.go
cmd/worker/main.go
internal/analysis/analysis.go
internal/pkgecosystem/ecosystem.go
internal/pkgecosystem/npm.go
internal/pkgecosystem/package.go
internal/pkgecosystem/pypi.go
internal/pkgecosystem/rubygems.go
internal/resultstore/result.go
internal/resultstore/resultstore.go
internal/sandbox/sandbox.go
sandboxes/npm/Dockerfile
sandboxes/pypi/Dockerfile
sandboxes/pypi/analyze.py
sandboxes/rubygems/Dockerfile
tools/README.md
tools/gvisor/README.md
tools/gvisor/runsc_compat.sh

Initial support of multiple phases of dynamic analysis.
This adds support for an "install" and "import" phase for each ecosystem.
Some changes:
- the podman container is started with a "sleep" and each phase is "exec"d in the same container.
- pcaps supported this nicely, but straces are for all phases are logged to one file. To handle this, the size of the log file is recorded before + after each phase so we can read the straces that apply only to the phase we are interested in.
- a `runsc_compat.sh` script was introduced to help `runsc` work with `podman`/`conmon` correctly for `exec`.
- the `pkgecosystem` logic was slightly refactored
- result storage now lives in `resultstore`

Support multiple phases of dynamic analysis

---

cmd/analyze/main.go
cmd/worker/main.go
internal/sandbox/sandbox.go

- Execute each phase in a start + exec + stop sequence to simplify log processing. Be aware this also means the "sleep" command now appears in the list of commands.
- Use a temp dir for logging for each phase so they aren't destroyed between each run
- Read the container ID from create rather than hardcoding a box id -> avoids issues if a container fails to be stopped/destroyed

Improve the multi-phase sandbox behavior

---

.github/workflows/build-images.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/test.yml

Remediate some of the scorecard results by adding `permissions:read-all` to all the workflows.

Apply read-all permissions to all the workflows.

---

internal/log/writer.go

Unfortunately bufio.Scanner has an internal buffer than can fill and return an error.
Instead use ReadBytes() which does not have this issue.

Handle lines of arbitrary size better.

---

internal/analysis/analysis.go
internal/analysis/output.go
internal/analysis/output_test.go
internal/sandbox/sandbox.go

The stdout and stderr is limited to the last 20 lines (max 4k bytes) from each.
This makes it easier to debug and measure the pipeline's quality.

Add a status, stdout and stderr to the results returned for each command

---

cmd/worker/main.go
internal/analysis/analysis.go

These log messages can be turned into metrics in GCP so we can measure the success/failure rates of the pipeline.

Add some logging so we can measure the behavior of the pipeline.

---

function/loader/README.md
function/loader/load.go
function/loader/schema.json

Autodetect fails to detect the new format, as many entries do not have
a "import" section.

Set schema during BQ load.

---

internal/sandbox/sandbox.go

Previously they were being passed after the image name, resulting in
them being passed as arguments to the container entrypoint ("sleep").

Fix volume arguments passed to sandbox.

---

internal/analysis/analysis.go
internal/packetcapture/packetcapture.go

- Use immediate mode to avoid any buffering, so our code gets the packets as soon as possible.
- Add a "done" signal to the goroutine, so all outstanding packets are processed after closing the pcap's handle.
It is possible that immediate mode may cause extra resource churn, but, according to the docs, it is possible for packets to remain undelivered if timeouts are used.
This attempts to fix #228

Limit any race conditions that might arise during packet capture.

---

cmd/analyze/main.go
sandboxes/npm/Dockerfile
sandboxes/npm/analyze.js
sandboxes/npm/bowerrc
sandboxes/pypi/Dockerfile
sandboxes/pypi/analyze.py
sandboxes/rubygems/Dockerfile
sandboxes/rubygems/analyze.rb

1. An install failure always causes the analysis to abort with an error - so it is easier to see when installs are failing. This may also be a signal for the quality of the library.
2. Add "wget" and "git" to the images to make sure packages that try to use them succeed.
3. Add "requests" and "urllib3" to the Python base image so that packages that _assume_ they're present succeed to run. setup.py hacks may also assume they exist.
4. Add a ".bowerrc" file to allow NPM packages using bower to install as root.
5. Pass "--pre" to pip to allow dev packages to be installed

Improve the functionality of the sandbox images so more packages run successfully and failures are more obvious

---

internal/sandbox/sandbox.go
tools/firewall/iptables.rules

This helps protect network based escapes from the Sandbox. It also blocks access to the kube-dns.
To ensure the sandbox can still resolve DNS, use the Google Public DNS for name resolution.

Block access from the Sandbox to any Private IP address space.

---

sandboxes/npm/Dockerfile
sandboxes/pypi/Dockerfile
sandboxes/rubygems/Dockerfile

`curl` is frequently used to exfiltrate data or pull down payloads so lets add it to sandboxes.
Helps improve #146

Add curl to the sandboxes to make them more representative.

---

internal/sandbox/sandbox.go

This helps fix #252.
We may want to go further than simply depending on podman to pick a name (e.g. we could just grab a word from a dictionary).

Remove the fixed box name to make it harder for sandbox detection.

---

.github/workflows/depsreview.yml

> This action scans your pull requests for dependency changes and will raise an error if any
> new dependencies have existing vulnerabilities. The action is supported
> by an API endpoint that diffs the dependencies between any two revisions.
- Included the https://github.com/actions/dependency-review-action
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

:seedling: Included dependency review action

---

function/loader/schema.json
internal/analysis/analysis.go
internal/dnsanalyzer/dnsanalyzer.go

DNS requests made during the analysis phase are stored and added to the analysis result.
Currently this only captures DNS over TCP or UDP. Any DNS queries over HTTPS or TLS are not captured.

Collect and add DNS queries to the analysis results.

---

README.md

This solves incompatible filesystem issues when podman attempts to run.
Fixes: #271

Update the README.md to include mapping the podman container path.

---

cmd/analyze/Dockerfile

GVisor added support for cgroups v2 in late 2022. This change updates GVisor to a version that includes these changes.
This will avoid the need to switch to cgroups v1 support and make it easier for people to use the project.
This should resolve #271.

Bump GVisor version. It now supports cgroups v2.

---

cmd/analyze/Dockerfile
cmd/analyze/main.go
cmd/worker/main.go
internal/analysis/analysis.go
internal/packetcapture/packetcapture.go
internal/sandbox/init.go
internal/sandbox/sandbox.go
tools/network/iptables.rules
tools/network/podman-analysis.conflist

`podman pull` can occur on the host after pcap is started, polluting the results with network noise.
This change puts the sandbox traffic onto a bridge network that can be captured separately to the host, removing any host traffic from the captured network traffic.

Separate sandbox traffic to avoid capturing host packets during analysis.

---

build/build_docker.sh
build/cloudbuild.yaml
cmd/analyze/Dockerfile
examples/e2e/README.md
infra/README.md

Don't push built images by default and bump Ubuntu to 22.04 for analysis image

---

cmd/analyze/Dockerfile

Remove deprecated apt-key command from Docker setup

---

build/build_docker.sh

This caused an outage - where the `rel-12` tag was missing from containers.

Make sure all tags are pushed during docker push.

---

internal/strace/strace.go

Replace [^\s] with \S in regexes

---

internal/sandbox/sandbox.go

Fixes #360.
Example:
```shell
$ ls -l /tmp/docker/
total 8
drwxrwxr-x 2 root root 4096 Sep 14 15:15 sandbox_logs_1902203493/
drwxrwxr-x 2 root root 4096 Sep 14 15:16 sandbox_logs_3929266306/
$ ls -l /tmp/docker/sandbox_logs_1902203493/
total 56884
-rw-r--r-- 1 root root 58227740 Sep 14 15:16 runsc.log.boot
-rw-r--r-- 1 root root     2770 Sep 14 15:15 runsc.log.create
-rw-r--r-- 1 root root     6304 Sep 14 15:16 runsc.log.gofer
-rw-r--r-- 1 root root     1749 Sep 14 15:15 runsc.log.start
```

Chmod the sandbox logDir so that it can be read by non-root users.

---

cmd/scheduler/main.go
examples/e2e/config/feeds.yml
tools/analysis/analysis_runner.py

This change adds full support for crates.io for Package Analysis.
Currently the analysis worker supports crates.io, but is not yet receiving work from the scheduler.
This change adds support to the scheduler. It also adds support to allow any package on crates.io to be ingested using the analysis_runner.sh script

Complete crates.io integration

---

infra/worker/scaler.yaml
infra/worker/workers-set.yaml

750 replicas was enough to process tens of thousands of requests per day.
The additional requested resources help avoid issues with the available CPU/memory when scheduling work.

Bump the replicas + requested resources to improve scalability.

---

.github/workflows/build-images.yml
.github/workflows/build.yml
.github/workflows/test.yml
README.md
cmd/analyze/Dockerfile
cmd/scheduler/Dockerfile
go.mod

Upgrade to use Go 1.19.1
Some dependencies no longer support Go 1.17, so it's time to update.

Upgrade to Go 1.19.1

---

run_analysis.sh

Fixes #390 
-  Can now pass in a package path to mount it inside the docker container and run local analysis on that file
-  Script prints out whether it's operating on a remote (web) package or local one, and prints the path/filename specified in the latter case
-  Refactored docker command to build arguments using bash arrays which avoids duplicating the command line

Improve run_analysis.sh script with local package functionality

---

examples/e2e/README.md
examples/e2e/docker-compose.yml

e2e docs are improved and include suggestions to fix issues that might arrise.
The docker-compose.yml also now points to the gcr.io version of the package-feeds image so it does not require auth.

Update the e2e docs and switch the scheduled-feeds image.

---

function/loader/load.go
function/loader/schema.json

Unfortunately the schema has changed, but the timestamp field will make querying easier.

Fix loader memory consumption issue by add time based partitions

---

cmd/analyze/main.go
cmd/worker/main.go
internal/analysis/rundynamic.go

Addresses remaining issue in #418, and fixes #406 as a replacement for #420

Move logging calls into rundynamic.go and make analysis image exit with error code if analysis fails

---

cmd/analyze/main.go
cmd/worker/main.go
internal/pkgecosystem/ecosystem.go

Refactors duplicate logic from `cmd/{worker,analysis}/main.go`, with slight behaviour changes:
1. The analysis version panicked if both a local package and an explicit version were specified on the command line. According to @calebbrown this behaviour is not necessary and can be removed
2. If `manager.Latest` returns a non-nil error, the log message changes from `Failed to get latest version` to `Error resolving package` and the log tags contain a key `"error": "failed to get latest version for package <package name>: <returned error info>"`
Are these acceptable?

Refactor package resolution logic out of cmd/{worker,analysis}/main.go

---

build/build_docker.sh

Shellcheck was giving a warning that paths should be quoted here

Fix shellcheck warning in build_docker.sh

---

internal/pkgecosystem/crates.io.go
internal/pkgecosystem/ecosystem.go
internal/pkgecosystem/npm.go
internal/pkgecosystem/package.go
internal/pkgecosystem/packagist.go
internal/pkgecosystem/pypi.go
internal/pkgecosystem/rubygems.go

This makes `Ecosystem` a specific type which centralises the definition of the string value and (when other parts of the code are refactored) makes usages into symbols

Introduce Ecosystem type

---

internal/staticanalysis/obfuscation/collect_data.go
internal/staticanalysis/parsing/js/babel-parser.js
internal/staticanalysis/parsing/js/js_parsing.go
internal/staticanalysis/parsing/js/js_parsing_test.go
internal/staticanalysis/parsing/parsing_types.go

This PR addresses two problems with the JS parser:
1. It could not handle certain variable declarations such as `let [a, b] = [1, 2];`
2. There was no way to differentiate between internal parser errors and syntax errors in the input to be parsed
For 1. the AST traversal was rewritten in the way anticipated in the comment to `traverseAst()` in the existing version of `babel-parser.js`:
> [A] simpler way to do it would be to just traverse until an actual Identifier node is found,
then figure what kind of identifier it is by inverting the logic for each case that currently is here.
Additional unit tests have been added to `js_parser_test.go` to cover the additional syntax parsing cases.
For 2. when the parser encounters a syntax error in the JS input, it now exits with a pre-defined exit …

JS parser improvements

---

internal/staticanalysis/parsing/js/babel-parser.js
internal/staticanalysis/parsing/js/js_parsing.go

This PR adds more types information to the JSON output of the JavaScript parser:
1. Code comments
2. Other information (currently just number of characters in input)
3. Syntax errors (optional) 
A future PR will add functionality to read this new information on the Go side.
Related to point 3, the parser can now be configured to be more tolerant of syntax errors during parsing. If enabled, any syntax errors that can be recovered from will be logged in the JSON output, alongside the parsed symbols. A command line flag to enable runtime configuration of this behaviour will be added in a future PR.
Finally, the format of the JSON output by the parser is changed slightly - the `array` key has been moved from the top-level JSON object to inside the `extra` dict, as it is applicable only to …

More improvements to JS parser

---

internal/staticanalysis/parsing/js/init_parser.go
internal/utils/archive_extract_test.go
internal/utils/write_file.go

Replace old octal format with new octal format, and use t.TempDir() in tests

---

CODE_OF_CONDUCT.md

Update the contact to the correct OpenSSF conduct contact (as confirmed on Slack)

Add correct contact to code of conduct

---

Makefile

This PR makes the following improvements to the Makefile
1. Standardises recipe names
2. Adds building of container and sandbox images
3. Adds buildah commands to sync locally built sandbox images to podman
4. Adds docker compose commands for e2e testing
There is still some remaining logic left over from the `build/build_docker.sh` script to bring over, in particular pushing of built images and adding a release tag if one is defined in the environment variables

Revolutionise Makefile

---

cmd/analyze/main.go
internal/worker/runstatic.go
sandboxes/staticanalysis/staticanalyze.go

This PR fixes some minor issues with the static analysis data flow. In particular:
1. JSON data from the sandboxed staticanalyze binary was being returned as bytes and then re-encoded into a base64 JSON string.
2. The format of the JSON saved to the static analysis bucket contained a redundant nested dictionary with `"obfuscation"` as the key

fix minor flaws in static analysis data flow

---

internal/staticanalysis/linelengths/line_lengths.go
internal/staticanalysis/linelengths/line_lengths_test.go
internal/staticanalysis/obfuscation/collect_data.go
internal/staticanalysis/obfuscation/data.go

This PR adds data relating to lengths of each line of source code to the `obfuscation.RawData` struct. This data is useful because obfuscated source sometimes consists of very long lines of code, with the special case of everything being on one line

Add line length counts to obfuscation.RawData

---

.github/workflows/build-images.yml
.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/depsreview.yml
.github/workflows/scorecards-analysis.yml
.github/workflows/shellcheck.yml
.github/workflows/test.yml

Dependabot recently gained the ability to update the commented version number when bumping dependency versions. However, this requires having the correct dependency version to begin with. This PR corrects the outdated version strings for Github action dependencies.
Fixes #427 (hopefully - there has been at least one report of the automatic version string updates not working) 

update version comment for github action dependencies

---

internal/staticanalysis/obfuscation/collect_data.go
internal/staticanalysis/obfuscation/collect_data_test.go
internal/staticanalysis/obfuscation/compute_signals.go
internal/staticanalysis/obfuscation/compute_signals_test.go
internal/staticanalysis/obfuscation/data.go
sandboxes/staticanalysis/staticanalyze.go

This PR does the following
- add detection of suspicious identifier names to signals. Currently this checks for identifier names that look like hex strings (#535) or just numeric with one prefix letter
- add crude detection of base64 strings. False positives are reduced by enforcing a minimum valid length for the string (currently 12 characters) and checking for existence of both a digit and a non-hex letter in the string. This detection may need to be improved to further reduce false positives
- improve naming of result struct fields: `Signals` -> `FileSignals`, `RawData` -> `FileData`
- improve comments

obfuscation improvements

---

internal/staticanalysis/obfuscation/base64/base64_detect.go
internal/staticanalysis/obfuscation/base64/base64_detect_test.go
internal/staticanalysis/obfuscation/compute_signals.go

1. Fix a bug where a whole list of candidate base64 strings were added to the result data structure instead of just the one being tested
2. Refactor base64 detection logic to its own package
3. Improve the heuristics used to limit false positives - it's easy to make a base64 string with no digits, so this was a poor heuristic; having at least one uppercase and one lowercase character is a much better heuristic
4. Add unit tests for base64 detection
5. Add better comments to functions
6. Make padding optional as not all variants of the standard require it
7. Increase minimum length of base64 strings to 16 as shorter strings are not as useful for obfuscation detection

Base64 detection improvements

---

batch-analysis/analyse-tarballs.sh

This is needed to support unattended remote batch analysis (e.g. nohup + ssh)

add -nointeractive flag to run_analysis.sh in batch script

---

internal/staticanalysis/obfuscation/data.go
internal/utils/hash_file.go
sandboxes/staticanalysis/Dockerfile
sandboxes/staticanalysis/staticanalyze.go

Adds SHA256 hashes of each package file, as well as the output of the `file` command run on each package file, to the static analysis output 
Fixes #576 

add file hashes and output of file command to static analysis data

---

batch-analysis/format-json.py

use `env python3` instead of `python3` in script

---

cmd/worker/main.go
internal/worker/runstatic.go
pkg/result/result.go

This PR adds functionality to the worker so that when a bucket path is configured in the environment variables, it will run static analysis on packages and upload the results to that bucket.
The environment variable config change will be added in another PR.  
Some refactoring was also done to worker.go:
- Extract logic into a new function for copying from a specified remote package bucket to a temp file
- Replace deprecated `ioutil.TempFile()` with `os.CreateTemp()`
- Extract logic into a new function for saving all the analysis results to their respective buckets
Finally, a new type `result.StaticAnalysisResults` was added to `pkg/results` to parallel `result.DynamicAnalysisResults`.

Enable worker to run static analysis when environment variable is set

---

examples/e2e/docker-compose.yml
infra/worker/workers-set.yaml

This change will enable static analysis in production when deployed

Add static analysis bucket config to worker config and docker-compose example

---

infra/worker/workers-set.yaml

Temporary reversion of the config change to enable static analysis, awaiting completion of #605 first

Don't enable static analysis in production (yet)

---

internal/worker/rundynamic.go
internal/worker/runstatic.go
sandboxes/staticanalysis/staticanalyze.go

Prints execution times for dynamic and static analysis to logs
Fixes #605 

log execution times for analyses and remove log.Label usages in staticanalyze.go

---

internal/staticanalysis/obfuscation/collect_data_test.go
internal/staticanalysis/obfuscation/compute_signals_test.go
internal/staticanalysis/parsing/js/js_parsing_test.go

Part 1 of #614 
- declare all cases in a single struct rather than variables for each test case. This reduces unnecessary names in the code.
- use parse results directly in compute_signals_test.go rather than having to regenerate them from parsing (and thus implicitly testing parsing)
Review note: it's a lot easier if you use the 'hide whitespace' option when viewing the diff

Refactor static analysis test files 

---

internal/staticanalysis/parsing/babel-parser.js
internal/staticanalysis/parsing/js_parsing.go
internal/staticanalysis/parsing/js_parsing_test.go
internal/staticanalysis/parsing/parsing_types.go

This PR does two main things: restructure the JS parser script with a view to implementing multi-file batch parsing, and improve passing of parse info and errors back to using JSON. 
Summary of changes:
1. use a proper data structure for storing parsing results rather than a global list of strings
2. move all code for parsing a single file into a function (that isn't the `main` function)
3. stop signalling syntax errors using the parser return code; instead output an Error object with a recognisable token
4. separate the output JSON data into two dicts: `tokens` which contains parsed tokens and `status` which contains info and errors  
5. add errors and info from parser output into the Go `parseOutput` struct
6. rename overloaded usages of `Symbol` in the parsing package
Signed-off-by: …

Parsing restructure and improvements

---

cmd/analyze/main.go
cmd/worker/main.go
internal/staticanalysis/obfuscation/file_signals_test.go
internal/worker/runstatic.go
sandboxes/staticanalysis/staticanalyze.go

- pass `staticanalysis.All` to RunStaticAnalysis() (renamed from `RunStaticAnalyses()`)
- improve some naming and comments under the static analysis package

minor static analysis code cleanup

---

Makefile
build/cloudbuild.yaml
scripts/run_analysis.sh

Switch from the old `build_docker.sh` script to the Makefile for production builds. Fixes #612.

make cloudbuild use Makefile

---

configs/e2e/docker-compose.yml

1. Add health checks to kafka and zookeeper
2. Use long-form depends_on to ensure dependents are only started when dependencies are health
3. Specify restart policies to keep failed services running

Make docker-compose more reliable.

---

internal/dynamicanalysis/analysis.go

the name `result` shadows an imported package name

fix name shadowing in dynamicanalysis/analysis.go

---

.github/workflows/build-images.yml
Makefile
examples/e2e/README.md
test/e2e/README.md

Having `docker_` prefixed to all the build recipes makes the Makefile more verbose to read and it takes longer to type out the recipe names. This PR removes the `docker_` prefix thus making the recipe names slightly shorter.

shorten Makefile recipes

---

function/loader/go.mod
function/loader/go.sum

Bump golang.org/x/net version in loader because Dependabot missed it

Loader net update

---

cmd/analyze/main.go
internal/staticanalysis/parsing/js_parsing.go
internal/staticanalysis/parsing/js_parsing_test.go

According to https://go.dev/ref/spec#Bootstrapping, `println` should not be relied upon to stay in the language. This PR changes usages of `println` to `fmt.Println` which is part of the standard library.

replace println with fmt.Println

---

cmd/analyze/main.go

The inbuilt help printing function already includes the default value for flag options, so adding it manually results in  duplicated "(default true)" text being output

remove duplicated default text for combined sandbox option

---

cmd/analyze/main.go
internal/utils/comma_separated_flags.go
sandboxes/staticanalysis/staticanalyze.go

This PR enables static analysis by default when run locally from the analysis image. It also required modifying the `utils.CommaSeparatedFlags()` function to allow multiple initial values for the flag.

Run static analysis locally by default

---

internal/log/log.go
internal/log/writer.go
internal/log/writer_test.go

`log.Initialize()` now returns `*zap.Logger` that can used for logging instead of the global logger.
This is a step towards solving #185.
In the process of implementing this change I started cleaning up the `Writer` implementation and adding tests - and discovered a race condition.
Basically, writes to the `io.Pipe()` writer may not be read by the reader and written the log before writer is closed and finished.
This is a result of the async goroutine consuming the reader.
The new implementation does not have this issue as writes are synchronously written to the log.

Prepare to move away from global logger + fix race condition in Writer

---

cmd/scheduler/main.go
cmd/scheduler/proxy/proxy.go

For #185.
Uses `*zap.Logger` directly, so we can make use of embedded context fields.

Use *zap.Logger in the scheduler, rather than the global log

---

internal/utils/hash_file.go
internal/utils/hash_file_test.go

Replace the usage of `os.ReadFile` which returns a `[]byte` containing the contents of the file to be hashed.
This is expensive, especially for large files and could potentially cause a denial-of-service if a large enough file is included in a package (in-particular one that zips efficiently so the zip is small, but the file is huge).
Instead, we use the fact that `hash.Hash` implements `io.Writer` to open the file and read it  using `io.Copy` instead. This ensures that memory consumption remains limited to the size of the buffer used inside `io.Copy`.

Update hashing implementation to reduce memory consumption

---

internal/staticanalysis/obfuscation/analyze.go
internal/staticanalysis/obfuscation/result.go

This field is currently unpopulated and we probably won't add code to populate it in this project, so we should remove it.

Remove suspicious files field from obfuscation results

---

cmd/analyze/main.go

Fixes issue in #683 - incorrect fatal loglevel when dynamic analysis does not finish successfully due to invalid package

fix incorrect error handling in analysis binary

---

cmd/analyze/main.go
cmd/worker/main.go
go.work.sum
internal/worker/sandbox_options.go

Split the sandbox option factory function into two - the mode was always a static arg and never a dynamic variable, so it isn't necessary. This allows for a reduction in state.
Additionally the logic to build up the option-specific args is now done prior to merging with the sandbox specific args.
Also updates `go.work.sum`

Simplify the passing of sandbox options around and reduce modality.

---

internal/worker/savefilewriteresults.go

This PR adds the version number to the filename of the zip file for write buffers so that newer versions don't overwrite the zipfiles of older versions.

Zipfile version fix

---

sandboxes/dynamicanalysis/Dockerfile

Defers copying of analysis scripts into the dynamic analysis sandbox image until the end of the build. This greatly improves caching and reduces build time when making iterative changes to the analysis scripts. 
Eventually, we should copy the desired analysis script in at runtime so it doesn't even need to be in the sandbox image.

Improve caching in dynamic analysis Dockerfile

---

internal/sandbox/sandbox.go

This PR adds a `CopyToHost` function to the `sandbox.Sandbox` interface which allows copying files from the sandbox container to the host, after the sandbox has run. This will be used in a future PR to save logs of executed functions during the dynamic analysis import phase. 
The current `copy` struct is slightly tweaked to allow dual use, and renamed to `copySpec` to avoid name shadowing. 
Also fixed an apparent bug with the existing copy implementation where multiple copies are specified - `podman cp` only supports one copy at once.

Allow copying files from sandbox to host

---

internal/sandbox/sandbox.go

Discovered as part of #741: if the sandbox fails to pull a new image, the init function will return and the `prune()` will not get called. This may cause extra space to be used. 
This PR switches the order of the two calls so that the prune comes first. Additionally, the error check of `createContainer` is changed to make it consistent in style with the other two.

sandbox: prune images before pulling new ones

---

internal/worker/logging.go

In logs, many errors coming from sandbox commands (usually during dynamic analysis) have minimal information in the error string itself. This change ensures that any stderr from these commands is also logged for debugging purposes

log stderr from command errors, if present

---

sandboxes/dynamicanalysis/Dockerfile

WORKDIR was changed (by me) to simplify copying of the analysis script files, but not properly restored to `/app`.
This broke some things, including causing #754. Thanks to @another-rex for diagnosing the problem!
Fixes #754.

fix bug in dynamic analysis dockerfile workdir

---

cmd/analyze/main.go
cmd/worker/main.go
infra/worker/scaler.yaml
infra/worker/workers-set.yaml
internal/featureflags/featureflags.go
internal/featureflags/featureflags_test.go
internal/featureflags/features.go
internal/strace/strace.go
internal/worker/save_data.go

Writing file contents in production is causing issues and needs to be toggled off.
Since enabling/disabling is a common pattern, this PR adds a feature flag library to make it very easy to control features.
In particular this will allow better control over production issues.
This change also updates prod configs to set the flag. Also introduces some logging refactor code too.

Add feature flags to make it easier to enable/disable features - specifically File Contents Saving

---

internal/utils/file_write_data_utils.go

fsync shouldn't be necessary as we don't care about persisting the file if the process is terminated without the buffers being flushed.

Remove an fsync to improve the performance of file writes.

---

cmd/downloader/README.md
cmd/downloader/main.go
go.mod
go.sum
internal/pkgmanager/download.go
internal/pkgmanager/ecosystem.go
internal/worker/resolvepackage.go

Add a new tool in the `cmd` directory which allows bulk downloading of packages. Usage is by passing a file of purls specifying which packages to download.

add package downloader tool and add more error handling to download functions

---

internal/resultstore/resultstore.go
internal/sandbox/sandbox.go
internal/staticanalysis/parsing/init_parser.go
internal/utils/archive_extract.go
internal/utils/archive_extract_test.go
internal/worker/rundynamic.go
sandboxes/staticanalysis/staticanalyze.go

The `path` and `filepath` packages in Go have been used fairly inconsistently in the project and sometimes incorrectly. `path` is intended for OS-independent path strings such as URLs, bucket paths, etc. whereas `filepath` is used for OS paths. 
In some cases, `filepath` functions were used instead of `path`, because a variable named `path` was shadowing the package name.
If we ever decided to run package analysis in a Windows environment, these incorrect usages would break things.
This PR restores the correct usages of `path` and `filepath`, and renames some variables to avoid shadowing package names

Correct usage of `path` and `filepath` packages across the project

---

internal/utils/archive_extract.go
pkg/api/analysisrun/result.go

move archive opening from `processGzipFile` into `ExtractTarGzFile` and add the missing close() call

Properly close archive after extraction

---

internal/featureflags/features.go
internal/sandbox/copy_args.go
internal/sandbox/copy_args_test.go
internal/sandbox/sandbox.go
internal/worker/rundynamic.go

- create execution log file in sandbox to enable code execution for PyPI (#730)
- add feature flag for code execution
- enable bidirectional copies via sandbox interface, rename existing `CopyToHost(src, dest)` function to `CopyBackToHost(hostPath, sandboxPath)` for clarity
- encapsulate logic for `podman cp` argument generation in a separate file (sandbox/copy_args.go) and add unit tests

Enable code execution for PyPI

---

sandboxes/dynamicanalysis/Dockerfile

This is just to silence a Scorecard warning, the actual behaviour is unchanged since the `--hash` option is already specified in the pypi-packages.txt file and this implicitly enables `--require-hashes`

explicitly use `--require-hashes` in pip install command

---

cmd/worker/pubsubextender/gcpdriver_test.go
infra/worker/workers-set.yaml

Adds some tests to check the GCP PubSub deadline bounds test.
Also disables immediate Nack'ing of messages when an error occurs. This means that messages won't be reprocessed until their deadline expires. This ensures that errors have a small (< 10min) delay before they're retried.
This should improve the responsiveness of the pipeline to live changes, and increase the chance that transient errors are successful on subsequent attempts.

More GCP PubSub tests and enable lazy nacks

---

internal/featureflags/features.go
internal/sandbox/sandbox.go
internal/worker/rundynamic.go

Some cleanups around the execution log feature
1. expose `Init()` in sandbox interface. This is needed because the copy commands require the sandbox to be initialised before the copy takes place
2. add `initialised` instance variable to `podmanSandbox` to track whether it has been initialised already, and remove explicit initialisation with null values in constructor
4. fix bug in execution log copy logic (wrong argument order)
5. consolidate result variables in RunDynamicAnalysis to avoid multiple copies of the same data
6. enable execution log feature flag by default in feature flags

Fix bugs in execution log handling

---

cmd/analyze/main.go

and rename existing feature flags option to match

Add option to print feature flags in analyze script

---

internal/staticanalysis/obfuscation/detections/suspicious_identifiers.go
internal/staticanalysis/parsing/string_regexp.go
internal/utils/combine_regexp.go
internal/utils/combine_regexp_test.go

This PR does some minor prework in anticipation of a larger PR which adds URL and IP address regex-based detection
1. Move the `combineRegexp` function to the `utils` package
2. Rename some of the suspicious identifier regexps
3. Minor logic cleanup in `FindStringsInCode`

Minor static analysis refactoring

---

internal/staticanalysis/basic_data.go
internal/staticanalysis/linelengths/line_lengths.go
internal/staticanalysis/linelengths/line_lengths_test.go
internal/staticanalysis/obfuscation/analyze.go
internal/staticanalysis/obfuscation/file_signals.go
internal/staticanalysis/obfuscation/file_signals_test.go
internal/staticanalysis/obfuscation/stats/sample_statistics.go
internal/staticanalysis/obfuscation/stats/sample_statistics_test.go
internal/staticanalysis/obfuscation/stringentropy/string_entropy.go
internal/staticanalysis/obfuscation/stringentropy/string_entropy_test.go
internal/staticanalysis/parsing/analyze.go
internal/staticanalysis/token/tokens.go
internal/utils/valuecounts/value_counts.go

Follow up to #838 as part of #836. Fixes #834 
High level changes:
1. move entropy calculations from obfuscation to parsing stage
2. fix bug in string entropy calculation
3. restructure tests for obfuscation.FileData
4. make GetLineLengths return integer slice rather than counted values
5. fix more json names
6. Don't use dict in `obfuscation.FileSignals` for suspicious identifiers
Still to do: improve unit tests for obfuscation.Analyze (e.g. URLs and IP address detection)

Remove entropy summaries and record string literal and identifier entropy as part of parsing phase

---

.github/workflows/build-images.yml
.github/workflows/build.yml
.github/workflows/test.yml
cmd/analyze/Dockerfile
cmd/scheduler/Dockerfile
cmd/scheduler/main.go
cmd/scheduler/proxy/proxy.go
go.mod
go.sum
internal/log/context.go
internal/log/context_test.go
internal/log/log.go
sandboxes/staticanalysis/Dockerfile

Go 1.21 added `log/slog`. This PR wires up Zap logger to slog, so that logs written to `slog` are handled by Zap.
This change also adds an `slog.Handler` for adding `slog.Attr`s to a context.

Enable log/slog from Go v1.21 and migrate scheduler.

---

internal/staticanalysis/parsing/babel-parser.js
internal/staticanalysis/parsing/js_parsing.go
internal/staticanalysis/parsing/js_parsing_test.go
internal/staticanalysis/parsing/parsing_types.go

Previously, string templates ended up as separate strings in the static analysis output. This PR changes the behaviour of string template parsing to keep the overall template string intact. Template expressions are replaced with the a placeholder string `"${}"` to avoid arbitrary code appearing in the processed string literal.
Some other minor improvements to comments in parsing_types.go and avoiding a panic in js_parsing.go are also included

JS parsing: Improve handling of string templates

---

sandboxes/dynamicanalysis/Dockerfile

Some malware fails when it calls "xxd" which is missing in the image. This change adds the command "xxd" to the dynamic analysis sandbox.

Add xxd to dynamic analysis sandbox.

---

function/loader/static-analysis-schema.json
internal/resultstore/result.go
internal/resultstore/resultstore.go
internal/worker/runstatic.go
internal/worker/save_data.go
internal/worker/savefilewriteresults.go

1. Introduce new top-level schema for static analysis data, consisting of `schema_version`, `key`, and `results` fields. `key` is an enhanced version of the `resultstore.pkg` struct which contains `ecosystem`, `name`, `version` fields to identify the package, and a `created` timestamp to store the analysis time. 
2. Make explicit `StaticAnalysisRecord` struct for serialised static analysis data that implements the above schema
3. Rename existing and `resultstore.result` struct to `DynamicAnalysisRecord` to match the static analysis one
4. Refactor save functions in ResultStore to identify which record struct is used, and extract default filename logic to its own function

Make explicit top-level structs for serialised analysis results

---

function/loader/static-analysis-schema.json
internal/resultstore/result.go
internal/resultstore/resultstore.go

This field needs to be at the top level in order to allow BigQuery to do time-based partitioning of the data

move `created` field to top level in static analysis schema 

---

function/loader/static-analysis-schema.json
internal/staticanalysis/signals/detections/escape_sequences.go
internal/staticanalysis/signals/file_signals.go
internal/staticanalysis/signals/file_signals_test.go
internal/staticanalysis/task.go
internal/staticanalysis/token/tokens.go

The `EscapedStrings` struct currently contains only the raw string literal for each detected value. This PR adds the parsed string value to the output struct. 
It also replaces calculation of the Levenshtein distance ratio with the absolute Levenshtein distance between the parsed and raw literals, since the ratio can be computed from the other quantities easily if desired. 
The Levenshtein distance function for string literals is now a method on the `token.String` object rather than a standalone function in the `detections` package

Add parsed string value to EscapedStrings struct

---

function/loader/static-analysis-schema.json
internal/resultstore/resultstore.go
internal/staticanalysis/analyze.go
internal/staticanalysis/analyze_test.go
internal/staticanalysis/basicdata/basic_data.go
internal/staticanalysis/basicdata/basic_data_test.go
internal/staticanalysis/parsing/analyze.go
internal/staticanalysis/parsing/analyze_test.go
internal/staticanalysis/parsing/result.go
internal/staticanalysis/result.go
internal/staticanalysis/signals/analyze.go
internal/staticanalysis/signals/file_signals.go
internal/staticanalysis/signals/file_signals_test.go
internal/staticanalysis/signals/result.go
internal/staticanalysis/task.go

This is a significant refactor such that static analysis results now consist of a single array of structs, where each struct contains all the static analysis information for that file (basic data, parsing, signals extracted)
Currently, each distinct static analysis task has a separate field in the top-level result struct, each with a separate list of structs containing filenames (which theoretically should all be identical across the structs for each task) and the other data obtained for that file. This makes the data schema unnecessarily complicated, and would make it harder to do data analysis because data from different tasks has to be joined by filename.
The top-level result struct now looks like
```go
type Result struct {
Files []SingleResult `json:"files"`
}
type SingleResult struct …
```

Static analysis: unify result struct into single array of file data

---

function/loader/static-analysis-schema.json
internal/resultstore/result.go
internal/resultstore/resultstore.go
internal/staticanalysis/analyze.go
internal/staticanalysis/analyze_test.go
internal/staticanalysis/basicdata/basic_data.go
internal/staticanalysis/basicdata/basic_data_test.go
internal/staticanalysis/parsing/analyze.go
internal/staticanalysis/parsing/analyze_test.go
internal/staticanalysis/parsing/result.go
internal/staticanalysis/result.go
internal/staticanalysis/signals/analyze.go
internal/staticanalysis/signals/file_signals.go
internal/staticanalysis/signals/file_signals_test.go
internal/staticanalysis/signals/result.go
internal/staticanalysis/task.go

This is a (retry of a) significant refactor such that static analysis results now consist of a single array of structs, where each struct contains all the static analysis information for that file (basic data, parsing, signals extracted)
Currently, each distinct static analysis task has a separate field in the top-level result struct, each with a separate list of structs containing filenames (which theoretically should all be identical across the structs for each task) and the other data obtained for that file. This makes the data schema unnecessarily complicated, and would make it harder to do data analysis because data from different tasks has to be joined by filename.
The top-level result struct now looks like
```go
type Result struct {
Files []SingleResult `json:"files"`
}
type …
```

Static analysis: unify result struct into single array of file data (second try)

---

.github/dependabot.yml

1. remove obsolete section for (now removed) static analysis gomod
2. check github actions updates weekly which allows for grouped PRs
3. add quotes to all time strings

clean up dependabot config and check for GH actions updates weekly

---

internal/worker/save_data.go
sandboxes/staticanalysis/staticanalyze.go

don't upload static analysis results when there is no data

---

internal/pkgmanager/pypi.go

This change returns a nil error if no URL is found for an artifact.
This conforms to the same behavior as Packagist, and causes the manager to return a `ErrNoArchiveURL` which is handled more gracefully.

Handle missing PyPI packages properly as well.

---

sandboxes/dynamicanalysis/Dockerfile

`dnsutils` adds the `nslookup` and `dig` commands, which can be used by malicious packages to exfil data.
The removal of `apt update` and `apt upgrade` helps speed up the docker image building by approx 1 minute (on my workstation)

Add `dnsutils` to dynamic analysis image + remove extra update/upgrades

---

cmd/worker/main.go
tools/analysis/analysis_runner.py

The feature was never used, and only supported dynamic analysis results. Newer bucket output never enabled override support.

Remove result_bucket_override support.

---

function/loader/static-analysis-schema.json
internal/staticanalysis/analyze_test.go
internal/staticanalysis/basicdata/basic_data.go
internal/staticanalysis/basicdata/basic_data_test.go
internal/staticanalysis/basicdata/describe_files.go

after some discussion around naming of this field, "detected_type" came out to be a more descriptive name than "description" without misusing the term "magic" or creating ambiguity using just "type"

static analysis: rename "description" field to "detected_type"

---

cmd/analyze/main.go
internal/dynamicanalysis/analysis.go
internal/featureflags/features.go
internal/log/log.go
internal/strace/strace.go
internal/strace/strace_test.go
internal/worker/rundynamic.go
scripts/run_analysis.sh

Update: reworked PR to disable strace debug logging by default, but add `StraceDebugLogging` feature flag for the analysis image, which saves the debug logs to a separate file in the analysis container. This allows saving and inspecting specifically the strace parsing logs, which may be useful for strace development in the future.
The logging calls with loglevel `Warn` (reporting parsing errors) are now logged to the default logger, which means they are still available in the main logs as before, in both the worker and analysis images.
Fixes #798. 
Original: Fixes #798 via supressing debug output of strace logs rather than redirecting it, since there is currently no clear need to redirect.
If there is a need to save the debug output, we can open another issue.

disable strace debug logging in worker, add feature flag to enable separate logging in analysis image

---

Makefile

Starting the e2e test can fail if the scheduler image was not built.
This PR adds a new Makefile recipe to build `test`-tagged images for all necessary images to run the e2e test.

add Makefile recipe to build test images for e2e test

---

function/loader/load.go

This is the final part of the static analysis data pipeline. Fixes #703 
I made the new static analysis loader function very similar to the existing dynamic analysis loader function, but kept it as a separate function rather than combining the two, so they can be debugged / modified separately.

add BigQuery loader function for static analysis

---

function/loader/load.go

Make the dynamic analysis `Load` function code consistent with the new `LoadStaticAnalysis` function 
- return errors instead of panicking
- reuse job waiting logic from `LoadStaticAnalysis()`
- add `bigquery.Close()` call

update dynamic analysis Load function

---

.github/workflows/codeql-analysis.yml

The CodeQL action is failing because of an outdated Go version.
I believe the issue is the same as in https://github.com/github/codeql-action/issues/1842#issuecomment-1704398087, so this PR adds the same fix, which is to add an explicit Go setup step with the correct version (1.21)

add explicit go setup step for CodeQL analysis

---

osv-scanner.toml

Required to silence OSV scanner warnings until https://github.com/google/osv-scanner/issues/634 is fixed

add alias of scanned vulnerability

---

internal/featureflags/features.go

Currently it is enabled via feature flag, this change makes it enabled by default (but can be turned off via feature flag)

enable code execution feature by default

---

cmd/analyze/main.go
internal/featureflags/featureflags.go

1. print errors for missing flags
2. better use of exit codes
3. [internal] consoliate `context` object initialisation

cmd/analyze: use exit status 1 and 2 for errors, improve error messages for invalid cli arguments

---

sandboxes/dynamicanalysis/analyze-python.py

This PR improves the automated execution capability of dynamic analysis, to support execution of async functions/methods and generator objects.
Async functions are awaited in a single-threaded manner and the result returned, while generator functions are iterated through and the results returned in a list.
Async generator functions are also supported, by combining the above approaches.

python dynamic analysis: support async and generator function execution

---

internal/strace/strace.go
internal/strace/strace_test.go

The unlink parsing regex did not support cases where unlink fails due to a nonexisting path, and so the strace log line had a missing path:
```
[ 23: 23] cmake X unlink(0x7f234e5bd500 ) = 0 (0x0) errno=2 (no such file or directory) (667ns)
```
Issue highlighted by `roboflex-visualization` package on pypi

strace parsing: fix regex issue when unlink syscall does not have path

---

.github/dependabot.yml

This reduces noise from dependabot PRs, but does not affect critical security updates. These are scanned independently of the specified update frequency.

reduce dependabot PR frequency to monthly

---

internal/staticanalysis/result.go
sandboxes/staticanalysis/staticanalyze.go

Add archive checksum 

---

internal/staticanalysis/analyze.go
internal/staticanalysis/analyze_test.go
internal/staticanalysis/basicdata/basic_data.go
internal/staticanalysis/basicdata/basic_data_test.go
internal/staticanalysis/result.go
sandboxes/staticanalysis/staticanalyze.go

This PR is a follow up to #978 and part of #959.
Static analysis now collects extra metadata about the archive file (file size and detected type, as well as SHA256 introduced in #978), and stores them in a new `ArchiveResult` struct which is part of the static analysis results.
To implement this, an `Option` pattern is introduced to the `basicdata.Analyze` function so that it can be reused for archive analysis, while also skipping over the line length analysis which is not relevant for binary files. 
For now, this new data is not written to the results JSON file and so not externally observable. This final step will be introduced in a future PR alongside a schema update.

static analysis: collect basic information about archive file

---

Makefile

This change is necessary because the docker daemon API has a minimum of
1.24, but buildah and podman use a minimum version of 1.22.
Using the save + load bypasses API issues by using the standard approach
to saving and loading images.

Move images using load/save instead of docker daemon.

---

.github/workflows/osv-scanner-pr.yml
.github/workflows/osv-scanner-scheduled.yml

This PR updates the osv-scanner action to use the new osv-scanner-action repo, and pins the action version.
cc @maxfisher-g ,@calebbrown

Switch to osv-scanner-action repo, pin action version

---

.github/workflows/test.yml

This allows the PRs to keep flowing.
#1015

Disable the currently failing crates.io test until it is fixed.

---

scripts/bq_load.sh

Reverts #1013
This reverts commit 836a6a2a0aa318a84492a43a16070c3da33a9d17.
`TRUNCATE` + `INSERT` failed, so reverting back to the `CREATE OR REPLACE`
#1000

Revert "Adjust the query to keep the destination rather than replace"

---

infra/cloudbuild/dynamic_loader/cloudbuild.yaml

This will cause the bq_load script to populate the live Dynamic Analysis table in BigQuery.

Point the new dynamic analysis loader at the real table.

---

.github/workflows/build.yml
cmd/analyze/Dockerfile
cmd/analyze/main.go
cmd/downloader/main.go
cmd/worker/config.go
cmd/worker/main.go
infra/worker/workers-set.yaml
internal/useragent/useragent.go
internal/useragent/useragent_test.go
sandboxes/staticanalysis/staticanalyze.go

Being a good API user means setting the user-agent field in outbound requests so our requests can be distinguished from others.
This change adds user-agent support.
Part of the implementation allows an "extra" component to be added to the user-agent. This is especially important as it allows our production environment to be distinguished from other runs.
To propagate this "extra" data to sandbox required some messing around with how environment variables are managed and configuration passed around in the `worker` process.
#1015

Add user-agents to http requests sent by Package Analysis

---

cmd/analyze/Dockerfile
internal/sandbox/sandbox.go

This change includes an additional flag to disable a new (2023-03) feature that keeps filesystem changes internal to GVisor, which breaks the start/stop/restart behavior of package analysis.

Bump GVisor to the latest release 20240212.

---

.github/workflows/build-images.yml
Makefile

Refactor docker/* targets in Makefile

---

.golangci.yml

Update the lint configuration to avoid errors.
This is a regression since `2024-05-03`. This blocks CI in PRs like #1050 , #1051, etc.
Alternatively, consider pinning the `version:` of `golangci-lint` used during CI: https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#version
The root cause is using a newer version of `golangci-lint` than the configuration used.
- https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md#v1580

golangci-lint: disable deprecated linters

---

.github/workflows/osv-scanner-pr.yml
.github/workflows/osv-scanner-scheduled.yml

osv-scanner-* workflows are failing because they need the `actions: read` permission.
This PR adds the permission to the workflows.

Update the perms to allow OSV scanning to work.

---

.golangci.yml

Also remove deprecated exportloopref and replace with copyloopvar

Rename deadline to the correct timeout so linting completes.
