CODE_OF_CONDUCT.md
Included CODE_OF_CONDUCT from https://github.com/ossf/scorecard/blob/main/CODE_OF_CONDUCT.md
=> Feat - Included CODE_OF_CONDUCT

SECURITY.md
=> Feat - Included SECURITY.md

.github/dependabot.yml
The dependabot config is broken.
=> Fix - dependabot config

.gitignore, analysis/README.md, analysis/customrules.yaml, hacks/falco/Dockerfile, hacks/falco/build_falco.bash, hacks/falco/libscap.patch
=> Add script for building our own falco.

.github/workflows/integration.yml, .github/workflows/ok-to-test.yml
Included https://github.com/imjohnbo/ok-to-test similar prow.
This is being used in Scorecard.
=> Feat - Included ok-to-test feature

analysis/config/deployment.yaml, analysis/go.mod, scheduler/config/deployment.yaml, scheduler/go.mod
https://github.com/ossf/package-analysis/issues/25
=> Update module names to reflect current namespace

analysis/python-runner.sh, build/build_docker.sh, build/python/Dockerfile, build/python/analyze.py, scheduler/main.go
=> Import installed python modules.

scheduler/README.md
This updates the README for the currently supported package types
=> scheduler/README.md: Update supported packages for npm & ruby

analysis/main.go
- Fix execve argument parsing when the command has "[" and "]" in them.
The regex wasn't able to handle this.
- Add creat, newfstatat argument parsing.
- Add info about whether if files were opened for read or write.
=> Various analysis improvements.

analysis/main.go, analysis/node-runner.sh, analysis/npm.go, analysis/pypi.go, analysis/python-runner.sh, analysis/ruby-runner.sh, analysis/rubygems.go, scheduler/main.go
This will be used for importing into BigQuery.
Also move command generation logic into the main analysis code from the
scheduler, and compute the latest version if not provided.
=> Add package name and version fields in resulting JSON file.

analysis/analysis.go, analysis/cmd/worker.go, analysis/config/deployment.yaml, analysis/npm.go, analysis/pypi.go, analysis/rubygems.go, build/analysis/Dockerfile, build/build_docker.sh
- Increase CPU/memory requests.
- Handle Pub/Sub receive errors properly.
- Flatten analysis images and cache this in the main analysis image
rather than pulling every run.
=> Analysis worker improvements.

analysis/README.md, analysis/analysis.go, analysis/cmd/analyze.go, analysis/cmd/worker.go, analysis/npm.go, analysis/pypi.go, analysis/rubygems.go
Also add documentation for running analysis locally.
=> Support analyzing local package archives.

.github/dependabot.yml
Updated dependabot for sub-packages.
=> :seedling: Update dependabot for sub-packages

analysis/analysis.go
Currently only RAW IP addresses are captured for `connect` calls.
Unfortunately this does not capture listening connections (e.g. a reverse shell, web server), or details about the port being used.
This change will capture:
- IPv4 and IPv6 sockets
- port information
- `bind`, `listen` as well as `connect` syscalls
Example output:
```
Sockets":[{"Address":"2a04:4e42:600::223","Port":443},{"Address":"2a04:4e42:200::319","Port":443},{"Address":"151.101.128.223","Port":443},{"Address":"151.101.0.223","Port":443},{"Address":"2a04:4e42:200::223","Port":443},{"Address":"2a04:4e42::223","Port":443},{"Address":"151.101.193.63","Port":443},{"Address":"151.101.192.223","Port":443},{"Address":"151.101.64.223","Port":443},{"Address":"151.101.129.63","Port":443},{"Address":"2a04:4e42::319","Port":443},{ …
```
=> Capture more data about network connections from strace output

analysis/analysis.go, cmd/analyze/main.go, cmd/worker/main.go, internal/pkgecosystem/ecosystem.go, internal/pkgecosystem/npm.go, internal/pkgecosystem/pypi.go, internal/pkgecosystem/rubygems.go
This is part of issue #149 to reorganize the repository to make it easier to read, extend and test.
=> Move package ecosystem code into a new pkgecosystem package.

analysis/analysis.go, internal/strace/strace.go
=> Extract the strace parsing into a separate internal package.

.github/workflows/build.yml, cmd/analyze/Dockerfile, go.mod, go.sum, internal/analysis/analysis.go, internal/dnsanalyzer/dnsanalyzer.go, internal/packetcapture/packetcapture.go
This helps solve issue #44.
Use the libpcap and gopacket library to collect and handle DNS traffic.
Can be extended to handle other types of traffic.
=> Collect network traffic and use it to extract DNS requests and responses.

README.md, go.mod, internal/analysis/analysis.go, internal/sandbox/sandbox.go, internal/strace/strace.go
- Order the strace output so that the json data is better suited to diffing
- Fix the hostname so that it is the same between invocations
See #147
=> Improve the strace and sandbox to facilitate diffing.

.gitignore, infra/terraform/analysis.tf, infra/terraform/docker_registry/main.tf, infra/terraform/docker_registry/variables.tf, infra/terraform/terraform.tfvars, infra/terraform/variables.tf
A simple config for managing Artifact Registry in GCP for a gcr.io redirection.
=> Add an initial Terraform config for managing GCP Artifact Registry for a gcr.io repo.

sandboxes/npm/analyze.js, sandboxes/pypi/analyze.py, sandboxes/rubygems/analyze.rb
This prepares the way for adding support to the analysis processor for capturing data in each distinct phases of analysis, rather than all at once.
=> Add support to the sandboxes for passing in a specific phase.

tools/analysis/analysis_runner.py
This helps with experimentation/testing by having access to a range of versions for a given package.
=> Extend analysis_runner.py for backfilling versions for a given package

cmd/worker/main.go, infra/worker/workers-set.yaml
Also make it actually optional.
=> Fix workers-set.yaml to include OSSF_MALWARE_ANALYSIS_PACKAGES.

cmd/analyze/main.go, cmd/worker/main.go, internal/analysis/analysis.go, internal/sandbox/sandbox.go
This should improve the reliability of the pipeline by not panicing needlessly.
=> Improve error handling and remove panics from library and worker code.

internal/sandbox/sandbox.go
This change does two things:
1. it improves the ability to debug the sandbox - knowing where the errors are being generated from.
2. fixes a bug with how errors during stop where being handled - particularly w.r.t "gofer is still running" errors.
(2) should improve the number of successful packages being parsed.
=> Improve the error messages and "gofer" handling during container "stop".

internal/strace/strace.go, internal/strace/strace_test.go
=> Support unlimited line length parsing for strace logs.

function/loader/load.go
=> Set MaxBadRecords for BigQuery loader.

docs/case_studies.md
- alt text for more images
- better explanation of these categories
=> Improve the case studies doc.

README.md
=> Update local commands to fix cgroups v2 issues.

.github/workflows/build-images.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/depsreview.yml, .github/workflows/scorecards-analysis.yml, .github/workflows/test.yml
Closes #294.
Here's a first pass on it, @calebbrown.
=> Ignore .md file changes for CI tasks

cmd/scheduler/main.go, internal/pkgecosystem/ecosystem.go, internal/pkgecosystem/packagist.go
Also adds support for filtering unwanted versions during scheduling.
=> Add Packagist feed support for analyzing PHP packages.

function/loader/schema.json, internal/analysis/analysis.go, internal/strace/strace.go, internal/strace/strace_test.go
=> add unlink/unlinkat parsing to strace.go, and add Delete field to FileInfo

.github/workflows/scorecards-analysis.yml
- Updated scorecard with the v2 beta
Signed-off-by: Naveen <172697+naveensrinivasan@users.noreply.github.com>
=> Updated scorecard with the v2 beta

.github/workflows/build-images.yml, .github/workflows/build.yml
=> Re-allow PRs changing only .md files to trigger CI builds

internal/strace/strace.go, internal/strace/strace_test.go
=> Fix out of bounds error in strace.go

function/loader/load.go
=> Bump the number of errors we accept during BQ loading.

function/loader/load.go
=> Bump even more because there are lots of errors.

build/build_analysis_docker.sh, run_analysis.sh
run_analysis.sh: runs analysis command on a given live package
build_analysis_docker.sh: rebuilds the local analysis docker image
=> Add helper scripts for analysis workflows

function/loader/schema.json
=> Add "Delete" to the schema for import.

.github/workflows/scorecards-analysis.yml
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Fixed the missing - Missing id-token write for scorecard action

sandboxes/crates.io/Dockerfile, sandboxes/npm/Dockerfile, sandboxes/packagist/Dockerfile, sandboxes/pypi/Dockerfile, sandboxes/rubygems/Dockerfile
=> Add sudo to sandbox images

run_analysis.sh
=> Add -nopull and dryrun options to run analysis script

run_analysis.sh
Missed a few bugs - quoting bug was picked up by [shellcheck](https://github.com/koalaman/shellcheck) running in IntelliJ.
=> Fix minor bugs in analysis script

cmd/analyze/main.go, cmd/worker/main.go, internal/dynamicanalysis/analysis.go, internal/dynamicanalysis/output.go, internal/dynamicanalysis/output_test.go, internal/pkgecosystem/crates.io.go, internal/pkgecosystem/ecosystem.go, internal/pkgecosystem/npm.go, internal/pkgecosystem/packagist.go, internal/pkgecosystem/pypi.go, internal/pkgecosystem/rubygems.go
=> Rename analysis package to dynamicanalysis

cmd/analyze/main.go, cmd/worker/main.go, internal/analysis/rundynamic.go, internal/dynamicanalysis/analysis.go, internal/pkgecosystem/ecosystem.go, internal/pkgecosystem/package.go
=> Refactor dynamic analysis run logic out of cmd/{analyze,worker}/main.go

.github/workflows/shellcheck.yml
=> Add shellcheck action

.github/workflows/shellcheck.yml
It was hopeless trying to get a shell command working in the Github actions file, so now it just calls the Makefile command
=> Try to finally make shellcheck action work properly

.github/workflows/shellcheck.yml
=> Fix syntax error in shellcheck action

cmd/analyze/main.go, internal/analysis/analysis_mode.go, internal/analysis/mode.go, internal/staticanalysis/task.go, internal/utils/comma_separated_flags.go, internal/worker/runstatic.go
...and add RunStaticAnalyses stub function (again)
=> Run static analysis from cmd/analyze/main.go

README.md, run_analysis.sh
=> Add version argument to run_analysis.sh and fix shellcheck warnings

internal/pkgecosystem/package.go
=> Remove unused field from pkgecosystem.Pkg

internal/pkgecosystem/download.go, internal/pkgecosystem/download_test.go, internal/pkgecosystem/ecosystem.go, internal/pkgecosystem/npm.go, internal/pkgecosystem/pypi.go
=> Add function to download package archives from NPM

internal/utils/archive_extract.go, internal/utils/archive_extract_test.go
Previously, archive (*.tar.gz) extraction would fail on archives where parent directories were not explicitly defined in the archive headers
=> Fig bug in archive extraction 

internal/staticanalysis/obfuscation/compute_signals.go, internal/staticanalysis/obfuscation/data.go, internal/staticanalysis/obfuscation/stats/sample_statistics.go, internal/staticanalysis/parsing/js/babel-parser.js, internal/staticanalysis/parsing/js/js_parsing.go
=> Add top-level result struct for obfuscation detection and helper functions for obfuscation structs

.github/workflows/test.yml, internal/staticanalysis/obfuscation/collect_data.go, internal/staticanalysis/obfuscation/compute_signals_test.go, internal/staticanalysis/parsing/js/init_parser.go, internal/staticanalysis/parsing/js/js_parsing.go, internal/staticanalysis/parsing/js/js_parsing_test.go, internal/utils/write_file.go, sandboxes/staticanalysis/staticanalyze.go
The initialisation involves writing the parser to a custom directory. This way no dependencies have to be installed beforehand (apart from NPM)
=> Add JS parser initialisation function and config struct

cmd/analyze/main.go
=> cmd/analyze/main.go: remove unnecessary function parameters

cmd/analyze/main.go, cmd/worker/main.go, internal/sandbox/sandbox.go, internal/worker/sandbox_options.go
=> introduce more sandbox configuration options; use for static analysis

cmd/analyze/main.go, cmd/worker/main.go, internal/sandbox/sandbox.go, internal/worker/runstatic.go, internal/worker/sandbox_options.go, sandboxes/staticanalysis/staticanalyze.go
=> Print static analysis results from analyze container

internal/staticanalysis/result.go, sandboxes/staticanalysis/go.mod, sandboxes/staticanalysis/staticanalyze.go
=> Output results from staticanalyze.go binary in JSON format

internal/staticanalysis/result.go, sandboxes/staticanalysis/Dockerfile
=> Fix sandbox sleep time and replace interface{} with any

.github/dependabot.yml
=> Configure dependabot for sandboxed static analysis binary

internal/sandbox/sandbox.go, internal/worker/sandbox_options.go
=> Add option for plain echoing of stdout and stderr from sandbox

.dockerignore, sandboxes/staticanalysis/Dockerfile
=> Fix static analysis container build

cmd/analyze/main.go, cmd/scheduler/main.go, cmd/worker/main.go, internal/log/log.go, internal/staticanalysis/obfuscation/collect_data_test.go, internal/staticanalysis/obfuscation/compute_signals_test.go, internal/staticanalysis/parsing/js/js_parsing_test.go, internal/strace/strace_test.go, internal/utils/archive_extract_test.go, sandboxes/staticanalysis/staticanalyze.go
Fixes #492
(plus slight import reorder)
=> Fix typo in log.Initialize()

internal/staticanalysis/parsing/js/js_parsing.go
=> Use parsing.SymbolType in parserOutputElement struct

README.md, run_analysis.sh
=> run_analysis.sh: pass through arguments to analysis binary as much as possible

internal/pkgecosystem/package.go, internal/worker/runstatic.go
=> Support static analysis of local packages

sandboxes/staticanalysis/go.mod, sandboxes/staticanalysis/go.sum
=> Run go mod tidy on staticanalysis sandbox go.mod, and update indirect dependency

sandboxes/staticanalysis/go.sum
=> Update go.sum for static-analysis sandbox

internal/staticanalysis/result.go
=> Improve comment to staticanalysis.Result

Makefile
=> Makefile: combine building and syncing sandbox images

internal/staticanalysis/obfuscation/collect_data.go, internal/staticanalysis/obfuscation/collect_data_test.go, internal/staticanalysis/obfuscation/data.go, internal/staticanalysis/parsing/js/js_parsing.go, internal/staticanalysis/parsing/parsing_types.go
=> Include source code comments in obfuscation raw data

internal/staticanalysis/obfuscation/compute_signals.go, internal/staticanalysis/obfuscation/compute_signals_test.go, internal/staticanalysis/obfuscation/data.go, internal/staticanalysis/obfuscation/stats/sample_statistics.go, internal/staticanalysis/obfuscation/stats/sample_statistics_test.go
=> Change string and identifier length statistics into proper count data in obfuscation.Signals

internal/staticanalysis/obfuscation/compute_signals.go, internal/staticanalysis/obfuscation/compute_signals_test.go, internal/staticanalysis/obfuscation/data.go, internal/staticanalysis/obfuscation/stats/sample_statistics.go, internal/staticanalysis/obfuscation/stats/sample_statistics_test.go, sandboxes/staticanalysis/staticanalyze.go
and rename `PackageSignals` to `PackageData`
=> Collect file sizes as part of obfuscation analysis

infra/worker/workers-set.yaml
Signed-off-by: Elaine Chien <elainechien@google.com>
=> Update config file to set environment variable for file writes bucket

Makefile
=> Add 'make test' recipe to Makefile which runs all Go unit tests

cmd/analyze/main.go, cmd/worker/main.go, internal/sandbox/init.go, internal/sandbox/sandbox.go
=> Rename sandbox.InitEnv to sandbox.InitNetwork and allow configuring offline sandbox

internal/staticanalysis/parsing/js/init_parser.go, sandboxes/staticanalysis/Dockerfile
=> Allow caching JS parser dependencies for staticanalyze sandbox

run_analysis.sh
=> add option to run script to fully disable network access for container (and fix help)

.github/dependabot.yml
=> remove unused path from dependabot config

internal/worker/rundynamic.go, pkg/result/result.go
Fixes #547
Signed-off-by: Ada Luong <adaluong@google.com>
=> Move DynamicAnalysisResults struct to public pkg/ directory

README.md
Signed-off-by: Ada Luong <adaluong@google.com>
=> Add note about analysis complete notifications subscription env

run_analysis.sh
=> add -nointeractive option to run script to allow running analyses in the background

docs/queries.md
These are queries that I've plugged into the BigQuery SQL Explorer to find malicious packages.
I created a table function to make it easier to change phase:
```sql
CREATE TABLE FUNCTION `ossf-malware-analysis.packages`.analysis_for_phase(phase STRING) AS (
SELECT Package, CreatedTimestamp, phase AS Phase,
CASE phase
WHEN "install" THEN Analysis.install
WHEN "import" THEN Analysis.import
END AS Result
FROM `ossf-malware-analysis.packages.analysis`
);
```
=> Add a query file with SQL queries used to find malicious packages.

internal/staticanalysis/parsing/js/babel-parser.js, internal/staticanalysis/parsing/js/js_parsing.go, internal/staticanalysis/parsing/js/js_parsing_test.go, internal/staticanalysis/parsing/parsing_types.go
=> js parsing: add support for BigInteger and Regexp literals

internal/staticanalysis/obfuscation/compute_signals.go, internal/staticanalysis/obfuscation/detections/base64.go, internal/staticanalysis/obfuscation/detections/base64_test.go, internal/staticanalysis/obfuscation/detections/escape_sequences.go, internal/staticanalysis/obfuscation/detections/escape_sequences_test.go
=> obfuscation: create detections package to hold individual detection checks/filters

internal/staticanalysis/obfuscation/detections/base64.go, internal/staticanalysis/obfuscation/detections/base64_test.go
=> fix bug in base64 detection

sandboxes/packagist/Dockerfile, sandboxes/pypi/Dockerfile, sandboxes/pypi/runtime-packages.txt, sandboxes/staticanalysis/Dockerfile
Fixes #572 (and should improve scorecard score!)
=> pin hashes of some unpinned dependencies in Dockerfiles

cmd/analyze/main.go, cmd/worker/main.go, internal/worker/rundynamic.go, internal/worker/runstatic.go, internal/worker/sandbox_options.go, sandboxes/staticanalysis/staticanalyze.go
=> Use file output and log analysis.Result for static analysis sandbox

cmd/scheduler/README.md
=> improve README.md in cmd/scheduler

cmd/worker/main.go
=> Add option to disable pulling sandbox images in worker

cmd/worker/main.go
This PR adds an internal struct type that contains sandbox image options to the binary. This way, image options are bundled together in function signatures so that they don't get too long.
=> Improved handling of 'nopull' option for worker binary

internal/utils/archive_extract.go
=> Fix nit in error assignment in archive_extract.go

cmd/analyze/Dockerfile
=> Add chmod 0700 to gvisor key directory in analysis Dockerfile

.github/workflows/build-images.yml, .github/workflows/build.yml
=> use Makefile and build staticanalyze binary in Github CI builds

internal/staticanalysis/parsing/input_strategy_test.go
=> add unit tests for input_strategy.go

cmd/analyze/main.go, cmd/worker/main.go, internal/worker/logging.go
=> remove extraneous log.Label usages

internal/staticanalysis/analyze.go
Rather than returning errors from individual tasks immediately, just log them and let processing continue.
Since the Obfuscation task relies on data from Parsing, also check that there is data from parsing to process.
=> don't let errors from individual static analysis tasks terminate overall analysis

internal/staticanalysis/result.go, internal/staticanalysis/task.go
This was meant to be part of #621 but was missed
=> rename "basic_data" to "basic" in static analysis results JSON

cmd/scheduler/main.go, cmd/worker/main.go
This PR removes the retry logic from the scheduler and worker.
Why?
(1) The primary reason is because docker-compose and kubernetes are better suited to handling retries.
The retries were previously needed because docker-compose was not configured correctly to wait until various services were healthy before starting dependents. #643 improve this for docker-compose so it is no longer an issue.
(2) The secondary reason is because the retry logic is flawed:
- the retry counter is never reset after a period with no errors
- the different causes are not taken into account (e.g. pub/sub being unavailable may resolve after 3 restarts, but what if an error is then caused by an IO issue)
- the delays never resets after a period with no errors
- if global state is broken a retry may just delay …
=> Remove retry logic as docker-compose and k8s handles it.

scripts/run_analysis.sh
Add check to the analysis script to ensure analysis image mounts an appropriate directory to `/var/lib/containers` inside the analysis image that is not backed by a non-overlay filesystem. For Github Codespaces, automatically falls back to using a temp directory, and for other environments, a manual override is requested.
Fixes #689
=> Fix analysis script error when /var/lib is backed by an overlay mount

scripts/analyse-tarballs.sh
=> analyse-tarballs.sh: add globbing of *.tar.gz files

internal/pkgmanager/crates.io.go, sandboxes/crates.io/analyze.py, sandboxes/dynamicanalysis/analyze-rust.py
=> Import Rust packages

internal/worker/rundynamic.go
1. move execution log retrieval to separate function 
2. don't attempt to read execution log if analysis already failed
3. change `log.Error` to `log.Warn` if execution log copy fails, since it's not actually present in any ecosystems yet
=> improve execution log retrieval

go.mod, go.sum, internal/dnsanalyzer/dnsanalyzer.go, internal/packetcapture/packetcapture.go
=> Switch unsupported google/gopacket to gopacket/gopacket

infra/worker/scaler.yaml, infra/worker/workers-set.yaml, internal/utils/file_write_data_utils.go
Also some minor fixes to the kubes configs.
=> Attempt to fix production by using mounts that aren't the overlay fs.

test/e2e/README.md
Fix some commands in `test/e2e/README.md` that don't work.
=> Fix commands in `test/e2e/README.md`

sandboxes/dynamicanalysis/Dockerfile
=> Fix PHP composer installation.

cmd/worker/main.go, cmd/worker/pubsubextender/extender.go, cmd/worker/pubsubextender/extender_test.go, cmd/worker/pubsubextender/gcpdriver.go, cmd/worker/pubsubextender/noopdriver.go
=> Add a package for posting ModifyAckDeadline messages to GCP periodically

cmd/worker/pubsubextender/extender.go, cmd/worker/pubsubextender/gcpdriver.go, cmd/worker/pubsubextender/gcpdriver_test.go, go.mod, internal/featureflags/features.go
- there was a bug when reading the deadline from GCP which didn't convert the value to seconds.
- GCP now has tests.
- added a feature flag to use noopDriver when disabled.
=> Fix a deadline bug, add GCP tests and a feature flag.

internal/log/log.go, sandboxes/staticanalysis/staticanalyze.go
and add deprecation marker to GetDefaultLogger
=> print static analysis errors using logger 

cmd/scheduler/main.go, internal/dynamicanalysis/analysis.go, internal/log/context.go, internal/log/context_test.go, internal/resultstore/resultstore.go, internal/strace/strace.go, internal/strace/strace_test.go, internal/utils/archive_extract.go, internal/worker/rundynamic.go, internal/worker/save_data.go
=> Move more logs over to slog.

cmd/analyze/main.go, cmd/worker/main.go, internal/dynamicanalysis/analysis.go, internal/log/writer.go, internal/log/writer_test.go, internal/sandbox/init.go, internal/sandbox/sandbox.go, internal/worker/rundynamic.go, internal/worker/runstatic.go
Context allows future SIGTERM handling.
=> Move the sandbox code over to slog and propogate context everywhere.

internal/pkgmanager/ecosystem.go, internal/pkgmanager/packagist.go, internal/resultstore/resultstore.go
Also handle the scenario where a download url is not available.
=> Fix Packagist JSON parsing to correctly parse dist fields.

internal/staticanalysis/parsing/js_parsing.go, internal/staticanalysis/parsing/js_parsing_test.go, internal/staticanalysis/parsing/parsing_types.go, internal/staticanalysis/token/identifier_type.go, internal/staticanalysis/token/position.go
and add doc comments for token.IdentifierType and token.Positiion
=> make token.IdentifierType into an integer enum 

.github/dependabot.yml, internal/staticanalysis/parsing/package-lock.json, internal/staticanalysis/parsing/package.json
add dependabot config for updates
=> Bump vulnerable @babel/traverse version

internal/worker/code_execution.go, internal/worker/rundynamic.go, pkg/api/analysisrun/phase.go, sandboxes/dynamicanalysis/analyze-node.js, sandboxes/dynamicanalysis/analyze-python.py
=> Add execute phase to dynamic analysis

infra/worker/workers-set.yaml
Currently, this only results in code execution for Python packages.
=> enable code execution feature in worker

.github/workflows/osv-scanner-pr.yml, .github/workflows/osv-scanner-scheduled.yml
This PR adds automatic vulnerability scanning using [OSV Scanner](https://github.com/google/OSV-scanner) 
Scanning is automatically triggered on opening PRs and pushes to main, as well as scheduled weekly.
=> Add OSV-Scanner github action

osv-scanner.toml
to silence vuln warning from OSV scanner which does not affect us
=> add osv-scanner.toml 

sandboxes/dynamicanalysis/Dockerfile
This means packages can compile python3 C extensions if desired
=> add python3-dev package to dynamic analysis dockerfile

cmd/analyze/main.go
When the package version is omitted from an analysis request, the version is automatically resolved to the latest available version. 
However, it is not correctly added to the logging context, so logs from the CLI analyze binary appear to have a blank version field. This PR fixes that.
Note: the same issue is also present in the worker binary, but since package feeds always provides the version anyway, there is not really any problem.
=> cmd/analyze: add resolved package version to logging context

infra/cloudbuild/dynamic_loader/cloudbuild.yaml
=> Add option to force cloud logging for BigQuery loading in cloudbuild.

infra/cloudbuild/dynamic_loader/cloudbuild.yaml
=> Set the entrypoint explicitly to /bin/bash in the BQ Loader cloudbuild.yaml

scripts/bq_load.sh
=> Add headless flag to BQ command to improve output.

scripts/bq_load.sh
=> Add option to BigQuery SQL to remove expiration from "like" table.
